dist: xenial
language: python
python: 3.7
cache:
  pip: true
install:
- pip install -r requirements.txt
script:
- cd ./dummydjangoproject
- "./manage.py test_compilemessages_ci"
before_deploy: "../archive.sh"
deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY}"
  secret_access_key: "${AWS_SECRET_KEY}"
  bucket: "foundation-site-translations"
  glob: translations.tgz
env:
  global:
  - ALLOWED_HOSTS=localhost
  - DEBUG=False
  - SECRET_KEY=secret
  - secure: sRjeywA1eP5J5uuPF17p4lt9Zi/vEF1ABmK0Q+uDRj2B3/+AEIoOL/iGmBtYdqgkcSnPhkyYO8Hslx8bcwa4ABg6wd4QclSz8CMSNg5ItONIyuAi9gFtwJe1rvLgAkPh8hEfgJvvpLoAsfYkAmBjv7pw94LwfS8l/6EH/wKz3MXBFksOavVPpSsv2wPilPh1WTrnK73bZYJhGUowI5+SBV+kLcYq/JTF4KRVz2aV0+BtoErgf3fvWmDUpgfrRuakmKs+mXaNiw7LZNrkq/Nuo3ara4w4O+CrkaCRDil+14EqVrhjHX6LTcQ936h/rzK60GLCVmkC5QSVxxvgkPepOnwOiXwmmzO0SStvbvEeht49xoA34Cv3Xkn3/NdE3DYNLe+EOfd2t3VD35aUlaraZLSk29KJLfDfJExXs4MtLmV+gqCgLo3pIRiLU+QuOX4DkQkw5fTHUCWxjZ4I/C/03AU/FSxZR9LY4Asdqz8HSmMLcmGN9AN96npEfZ5nZiNXZOy8kn3Uq9Tl9TRiF4c38lEGIK6SDKozgL/HiJHV2NpYba+llWqni+aIGMXjQLwHREo06GVkqOh/W39ppN7k2B+t++O+Tl5DTOYquHO0SKi51y28Dt8MnQ2wpf6Sm5X8VwkyOa8Efy5V1YQUja8GqAARBdoxrTJWXpQUBhich5Y=
  - secure: vohBj40xDAuJPvX9AawLPv4uH2SrxQgm/jst5oeYHdIWF3zBhOTB7HPJrWzXbD1soyzbvLYxdDFp77ryJy66L+IkesUcHi7IocWgEtgLqGl35hck+cB9v35eIslXSBFRxMsduj41qZVq2j66G7mzEcZRS9zqiXOSu/ClV5JGRQw4i9FJ3Yfikon439UUuq6rFZmHBZieIb9vFphaMJICY7sqi+/oBHk6nGu/IoSN4NqK85BLMYBXJxo2EiLGWL1v178T3KSg1ig40uxhzFyhu1oGcm3SCJLrTt8ZBszIyM31mb7NmU/UMfhPHl0soFfpmkSd8ClDq2w0ARuUCuXqzMGeFJyDhQtuh3mYQhZzJ3jv0HyXZD+FMFK2xT4Fv64OsKSW4fXDkTnNi/Ijqi4r1iXUnRkD4AqpNd66jzzDu645PmcXRBibJcJeu1cbAb+UNUj4Sitxx83FJ4Vmjb+ORfaawgVsBKKVHSocaFPQfl9fIFPaDg/37ejBlg7Cvh7s28KaX7Cn4JR9nyDyLAX9y2nKNr9eecOrf0K+c3zQUG8Tydd6RuQyXc3hu9f5yLFKoSmCiWSenOj0CxK/4dHeP6zQl0l1Bzfol+VbnLcbmV99p8cBImrm0xkThA5gDSJPWQeAx1xrmwHbq6GGmCS/ZbEDuyUN7JjFsgvQJj0IeLs=
  - secure: r3ET7uOc4vWoOnGJaOmMVkLGX/K9R5dHo5lQwFu2guFf0MPFnqIH4qddzuRstOfnejD6gD5c/jdwbq6d/2q1TLbuJPnEoLDOVsEmNrC3tJhjwirz7F0Fh3D+rFO6NYn7UDZd4zjAqAIkjzAjbG1mbZA4e1RCNo2a+oKSe0TSVd04M7yjaFe3vjoatpPi7n+gYvuZjW10WCQvytPSorjMfyoY2l8oDSx1aR+lkiExgGK7ChqZ6W88wNeIdYsjXvXUeajJxLO2hfLwirHK79UYX7gYGPo2TJ4nP1M42nZN+vgIX5KT3EJXPuToQ3Pl21mQoo1rHtIaeXoIh10LHeAXTwlatw9Z+OulTJneuJDfNPKGORwP3EFVk2mnLSV6x9IaT98qfGJA4aRb1js6pk0zGL4IZeOMl9Px49QfglFxD/ogoZbn2m8HEAAYHqf4TgdAxkIRFy60Tf165sQ5CQY28uvn+7yMJp4wdj3YCMbLVg8WQ6a6bMOCwujwUYcKPqr1TXnT6bJWb5pZDf9Sc32BA5O4TpIVjrB1xjp3mA17urSbOKj2WnykC03L3qA0kffjKDtEeqfCS+oNdWzVkHxkz5lcjSI8WMELYs+4kxvMQvdiwOXzelqOEXeAAJkx/OOhW9csXOvY9UFl+5qioj1p8yzwRphPfEWyhY+4yZ1Sin0=
