dist: xenial
language: python
python: 3.7
cache:
  pip: true
install:
- pip install -r requirements.txt
script:
- cd ./dummydjangoproject
- "./manage.py test_compilemessages_ci"
# TODO Make the deploy step only available on master
before_deploy: ./archive.sh
env:
  global:
  - ALLOWED_HOSTS=localhost
  - DEBUG=False
  - SECRET_KEY=secret
  - secure: sRjeywA1eP5J5uuPF17p4lt9Zi/vEF1ABmK0Q+uDRj2B3/+AEIoOL/iGmBtYdqgkcSnPhkyYO8Hslx8bcwa4ABg6wd4QclSz8CMSNg5ItONIyuAi9gFtwJe1rvLgAkPh8hEfgJvvpLoAsfYkAmBjv7pw94LwfS8l/6EH/wKz3MXBFksOavVPpSsv2wPilPh1WTrnK73bZYJhGUowI5+SBV+kLcYq/JTF4KRVz2aV0+BtoErgf3fvWmDUpgfrRuakmKs+mXaNiw7LZNrkq/Nuo3ara4w4O+CrkaCRDil+14EqVrhjHX6LTcQ936h/rzK60GLCVmkC5QSVxxvgkPepOnwOiXwmmzO0SStvbvEeht49xoA34Cv3Xkn3/NdE3DYNLe+EOfd2t3VD35aUlaraZLSk29KJLfDfJExXs4MtLmV+gqCgLo3pIRiLU+QuOX4DkQkw5fTHUCWxjZ4I/C/03AU/FSxZR9LY4Asdqz8HSmMLcmGN9AN96npEfZ5nZiNXZOy8kn3Uq9Tl9TRiF4c38lEGIK6SDKozgL/HiJHV2NpYba+llWqni+aIGMXjQLwHREo06GVkqOh/W39ppN7k2B+t++O+Tl5DTOYquHO0SKi51y28Dt8MnQ2wpf6Sm5X8VwkyOa8Efy5V1YQUja8GqAARBdoxrTJWXpQUBhich5Y=
