dist: xenial
language: python
python: 3.7
cache:
  pip: true
install:
- pip install -r requirements.txt
script:
  - cd ./dummydjangoproject
  - ./manage.py test_compilemessages_ci
env:
  global:
    - ALLOWED_HOSTS=localhost
    - DEBUG=False
    - SECRET_KEY=secret
    - secure: KeLHXKyLXq/vJ2Z6Gus718QJjYM1AAwL8G6gocLuWNpQ31sPALuCEihT2Q3nU/P6q/TjUFW5Rr2f1Hqu6z+U5PIYFhWnlqQ+2IBhL4QTvJo9tvRDvfUcwld5pVtI+bYfQwOeVqL3ZeBzVcQcH0dcafxMRnGvotJ9Wp72nbRK4zZPBeOE0HCl8E26P+ojxpW4i12Z6p3b8I/sXRoizpgAiscVrpIbWGFEKJ3zyPxp/4oQNy2zT+viXR76dc8/Cd83v/bWgIo2ahW4UDdcKj+2bi66SiOV17RJ8uPGcf/HZpkhrHvONplGWKwzWTlQ02k316IXMIcNMuFebgvG1pQ+xvEk4nZ5+20S9LJ7BgB87vRljIyIMMqSz/WCUjDkhLCOkSmwmDi4vJzSxbGdyBl4VXJ++A1jGEbD3GXbsAUqQ3DKvxJ1fKbfpJroajyQepJL9UmwBUE50jgpCmOYKt50YqxbguxswmnP9rT36raej4MrDmduVU2m84sVjOMtwfjRHXIhnSdKaTgDBZSIIjH58ikBDr/b9FRBHo/r3WqJPgbtzeEjLnU6AGir30jRpFmaVb0iwU4EyVTNmSJxfO5fZ5XZux0zhRH62FivaKL1daMaPGLhIGb4kvJgrRKrpixWcqKjQ8uAJLl6hnRWEtYBpFCw2EIeRYrqC4BcNkmqf/Q=
