locales = [ "de", "fr"]

[[paths]]
reference = "foundation/translations/networkapi/buyersguide/locale/django.pot"
l10n = "foundation/translations/networkapi/buyersguide/locale/{locale}/LC_MESSAGES/django.po"

[[paths]]
    reference = "foundation/translations/networkapi/buyersguide/templates/about/locale/django.pot"
    l10n = "foundation/translations/networkapi/buyersguide/templates/about/locale/{locale}/LC_MESSAGES/django.po"
    locales = [
        "fr"
    ]
