locales = [ "de", "fr"]

[[paths]]
reference = "django/translations/networkapi/buyersguide/locale/django.pot"
l10n = "django/translations/networkapi/buyersguide/locale/{locale}/LC_MESSAGES/django.po"
