locales = [ "de", "fr"]

[[paths]]
reference = "dummydjangoproject/translationstests/networkapi/buyersguide/locale/django.pot"
l10n = "dummydjangoproject/translationstests/networkapi/buyersguide/locale/{locale}/LC_MESSAGES/django.po"
