locales = ["de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR", "sw"]

[[paths]]
reference = "foundation/translations/networkapi/wagtailpages/templates/buyersguide/locale/django.pot"
l10n = "foundation/translations/networkapi/wagtailpages/templates/buyersguide/locale/{locale}/LC_MESSAGES/django.po"

[[paths]]
    reference = "foundation/translations/networkapi/wagtailpages/templates/about/locale/django.pot"
    l10n = "foundation/translations/networkapi/wagtailpages/templates/about/locale/{locale}/LC_MESSAGES/django.po"
    locales = [
        "de", "es", "fr", "pt-BR"
    ]

[[paths]]
    reference = "foundation/translations/networkapi/templates/pages/buyersguide/about/locale/django.pot"
    l10n = "foundation/translations/networkapi/templates/pages/buyersguide/about/locale/{locale}/LC_MESSAGES/django.po"
    locales = [
        "de", "es", "fr", "pt-BR"
    ]
