locales = [ "de", "es", "fr", "nl", "pl", "pt_BR"]

[[paths]]
reference = "django/translations/locale/django.pot"
l10n = "django/translations/locale/{locale}/LC_MESSAGES/django.po"

[[paths]]
reference = "django/translations/locale/messages.ftl"
l10n = "django/translations/locale/{locale}/messages.ftl"
