locales = ["de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR", "sw"]

[[paths]]
reference = "foundation/translations/locale/django.pot"
l10n = "foundation/translations/locale/{locale}/LC_MESSAGES/django.po"

[[paths]]
reference = "foundation/translations/locale/djangojs.pot"
l10n = "foundation/translations/locale/{locale}/LC_MESSAGES/djangojs.po"

[[paths]]
reference = "foundation/translations/legacy_apps/locale/django.pot"
l10n = "foundation/translations/legacy_apps/locale/{locale}/LC_MESSAGES/django.po"

[[paths]]
reference = "foundation/translations/legacy_apps/locale/djangojs.pot"
l10n = "foundation/translations/legacy_apps/locale/{locale}/LC_MESSAGES/djangojs.po"

[[paths]]
    reference = "foundation/translations/legacy_apps/wagtailpages/templates/wagtailpages/pages/locale/django.pot"
    l10n = "foundation/translations/legacy_apps/wagtailpages/templates/wagtailpages/pages/locale/{locale}/LC_MESSAGES/django.po"
    locales = [
        "de", "es", "fr", "fy-NL", "nl", "pt-BR"
    ]

[[paths]]
    reference = "foundation/translations/legacy_apps/wagtailpages/templates/wagtailpages/pages/youtube-regrets-2021/locale/django.pot"
    l10n = "foundation/translations/legacy_apps/wagtailpages/templates/wagtailpages/pages/youtube-regrets-2021/locale/{locale}/LC_MESSAGES/django.po"
    locales = [
        "de", "es", "fr", "nl", "pt-BR"
    ]

[[paths]]
    reference = "foundation/translations/legacy_apps/wagtailpages/templates/wagtailpages/pages/youtube-regrets-2022/locale/django.pot"
    l10n = "foundation/translations/legacy_apps/wagtailpages/templates/wagtailpages/pages/youtube-regrets-2022/locale/{locale}/LC_MESSAGES/django.po"
    locales = [
        "de", "es", "fr", "nl", "pt-BR"
    ]
