locales = [ "de", "es", "fr", "nl", "pl", "pt_BR"]

[[paths]]
reference = "dummydjangoproject/translationstests/locale/django.pot"
l10n = "dummydjangoproject/translationstests/locale/{locale}/LC_MESSAGES/django.po"

[[paths]]
reference = "dummydjangoproject/translationstests/locale/messages.ftl"
l10n = "dummydjangoproject/translationstests/locale/{locale}/messages.ftl"
