locales = ["de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR"]

[[paths]]
reference = "foundation/translations/legacy_apps/mozfest/locale/django.pot"
l10n = "foundation/translations/legacy_apps/mozfest/locale/{locale}/LC_MESSAGES/django.po"
