locales = ["de", "es", "fr", "fy_NL", "nl", "pl", "pt_BR"]

[[paths]]
reference = "foundation/translations/networkapi/mozfest/locale/django.pot"
l10n = "foundation/translations/networkapi/mozfest/locale/{locale}/LC_MESSAGES/django.po"
